---
- hosts: localhost
  tasks:

    - name: Copia o token para entrada de novos nós no cluster em um arquivo
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command.sh"